server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://admin:testor@127.0.0.1:27017
      #      username: admin
      #      password: testor
      #      host: 127.0.0.1
      #      port: 27017
      database: surfbuddies


jwt-security:
  secret: MySuperDuperPseudoSecret-IMPORTANsdf34523452T-Must_ChAn!ge23sdfhjj6-[0-4gdf
  expirationTimeInDays: 1
